services:
    _defaults:
        autoconfigure: true

    Terminal42\TableLookupWizardBundle\AddAssetsListener:
        arguments:
            - "@assets.packages"
            - "@request_stack"
            - "@contao.routing.scope_matcher"
